schemes = {
    "J&K Bank Nano Udaan": [
        {
            "Enterprise Type": "Nano Enterprise",
            "Eligible Category": "General",
            "Min Project Cost": 0,
            "Max Project Cost": 1000000,
            "Margin (%)": 10,
            "Subsidy (%)": 25,
            "Subsidy Cap": 100000,
            "Interest Subvention (%)": 5,
            "Interest Subvention Cap": 50000,
            "Min Age": 18,
            "Max Age": 59,
            "Location": "J&K",
            "Sectors Served": "All sectors (see note)",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "No prior default under govt schemes; new unit; no education req.; not for expansion"
        },
        {
            "Enterprise Type": "Nano Enterprise",
            "Eligible Category": "Women / PWD (>=40% disability)",
            "Min Project Cost": 0,
            "Max Project Cost": 1000000,
            "Margin (%)": 10,
            "Subsidy (%)": 30,
            "Subsidy Cap": 100000,
            "Interest Subvention (%)": 5,
            "Interest Subvention Cap": 50000,
            "Min Age": 18,
            "Max Age": 59,
            "Location": "J&K",
            "Sectors Served": "All sectors (see note)",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Same as above"
        }
    ],
    "J&K Bank MSME Aghaaz": [
        {
            "Enterprise Type": "Micro MSME (Focus/Sunrise)",
            "Eligible Category": "Micro",
            "Min Project Cost": 1000001,
            "Max Project Cost": 25000000,
            "Margin (%)": 20,
            "Subsidy (%)": 0,
            "Subsidy Cap": 0,
            "Interest Subvention (%)": 6,
            "Interest Subvention Cap": 500000,
            "Min Age": 18,
            "Max Age": 59,
            "Location": "J&K",
            "Sectors Served": "Focus & Sunrise Sectors",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Domicile; no default (self/family); prior loans repaid 6+ mo ago; new unit only"
        },
        {
            "Enterprise Type": "Small MSME (Focus/Sunrise)",
            "Eligible Category": "Small",
            "Min Project Cost": 25000001,
            "Max Project Cost": 250000000,
            "Margin (%)": 20,
            "Subsidy (%)": 0,
            "Subsidy Cap": 0,
            "Interest Subvention (%)": 6,
            "Interest Subvention Cap": 3000000,
            "Min Age": 18,
            "Max Age": 59,
            "Location": "J&K",
            "Sectors Served": "Focus & Sunrise Sectors",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Same as above"
        },
        {
            "Enterprise Type": "Medium MSME (Focus/Sunrise)",
            "Eligible Category": "Medium",
            "Min Project Cost": 250000001,
            "Max Project Cost": 1250000000,
            "Margin (%)": 20,
            "Subsidy (%)": 0,
            "Subsidy Cap": 0,
            "Interest Subvention (%)": 6,
            "Interest Subvention Cap": 7500000,
            "Min Age": 18,
            "Max Age": 59,
            "Location": "J&K",
            "Sectors Served": "Focus & Sunrise Sectors",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Same as above"
        }
    ],
    "J&K Bank Yuva Parwaaz": [
        {
            "Enterprise Type": "Micro/Small Enterprise",
            "Eligible Category": "Existing Micro & Small",
            "Min Project Cost": 1000001,
            "Max Project Cost": 25000000,
            "Margin (%)": 20,
            "Subsidy (%)": 0,
            "Subsidy Cap": 0,
            "Interest Subvention (%)": 6,
            "Interest Subvention Cap": 1000000,
            "Min Age": 18,
            "Max Age": 59,
            "Location": "J&K",
            "Sectors Served": "All (see eligible list)",
            "Project Purpose": "Expansion Only",
            "Other Eligibility": "Business ≥5 yrs in J&K; domicile; for expansion; not for new units; past loans repaid 6+ mo ago"
        }
    ],
    "PMEGP": [
        {
            "Enterprise Type": "Micro Enterprise",
            "Eligible Category": "General, Urban",
            "Min Project Cost": 0,
            "Max Project Cost": 2500000,
            "Margin (%)": 10,
            "Subsidy (%)": 15,
            "Subsidy Cap": None,
            "Interest Subvention (%)": 0,
            "Interest Subvention Cap": 0,
            "Min Age": 18,
            "Max Age": None,
            "Location": "India (Rural/Urban)",
            "Sectors Served": "All except negative list",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Only new units; no prior subsidy, 1/family, >₹10L manuf or >₹5L service req VIII pass; SC/ST/OBC/subcats min 5% self"
        },
        {
            "Enterprise Type": "Micro Enterprise",
            "Eligible Category": "General, Rural",
            "Min Project Cost": 0,
            "Max Project Cost": 5000000,
            "Margin (%)": 10,
            "Subsidy (%)": 25,
            "Subsidy Cap": None,
            "Interest Subvention (%)": 0,
            "Interest Subvention Cap": 0,
            "Min Age": 18,
            "Max Age": None,
            "Location": "India (Rural/Urban)",
            "Sectors Served": "All except negative list",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Same as above"
        },
        {
            "Enterprise Type": "Micro Enterprise",
            "Eligible Category": "SC/ST/OBC/Minority/Women/PHC/NER/Hill/Border, Urban",
            "Min Project Cost": 0,
            "Max Project Cost": 5000000,
            "Margin (%)": 5,
            "Subsidy (%)": 25,
            "Subsidy Cap": None,
            "Interest Subvention (%)": 0,
            "Interest Subvention Cap": 0,
            "Min Age": 18,
            "Max Age": None,
            "Location": "India (Rural/Urban)",
            "Sectors Served": "Special Categories",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Same as above"
        },
        {
            "Enterprise Type": "Micro Enterprise",
            "Eligible Category": "SC/ST/OBC/Minority/Women/PHC/NER/Hill/Border, Rural",
            "Min Project Cost": 0,
            "Max Project Cost": 5000000,
            "Margin (%)": 5,
            "Subsidy (%)": 35,
            "Subsidy Cap": None,
            "Interest Subvention (%)": 0,
            "Interest Subvention Cap": 0,
            "Min Age": 18,
            "Max Age": None,
            "Location": "India (Rural/Urban)",
            "Sectors Served": "Special Categories",
            "Project Purpose": "New Enterprise",
            "Other Eligibility": "Same as above"
        }
    ]
}